export const ALL_FILMS = [
  '10 Cloverfield Lane',
  '2001: A Space Odyssey',
  'Harry Potter and the Philosopher’s Stone',
  'I, Robot',
  'A Quiet Place',
  '12 Angry Men',
  '12 Years A Slave',
  '127 Hours',
  '13th',
  '1917',
  '1984',
  '20,000 Days on Earth',
  '2046',
  '20th Century Women',
  '21 Grams',
  '24 Hour Party People',
  '25th Hour',
  '28 Days Later',
  '3 From Hell',
  '3 Women',
  '30 Days of Night',
  '300',
  '31',
  '35 Shots of Rum',
  '42nd Street',
  '45 Years',
  '5 Dolls for an August Moon',
  '500 Days of Summer',
  '71 Fragments of a Chronology of Chance',
  '8 1/2',
  '9 Songs',
  'A Bay of Blood',
  'A Beautiful Day In The Neighborhood',
  'A Bigger Splash',
  'A Clockwork Orange',
  'A Cock and Bull Story',
  'A Cure For Wellness',
  'A Dangerous Method',
  'A Date for Mad Mary',
  'A Field In England',
  'A Fistful of Dynamite',
  'A Ghost Story',
  'A Girl Walks Home Alone at Night',
  'A Glimpse Inside The Mind Of Charles Swan III',
  'A Good Woman Is Hard To Find',
  'A Hard Days Night',
  'A Hidden Life',
  'A History of Violence',
  'A Hitchhiker’s Guide To The Galaxy',
  'A Hologram for the King',
  'A Horrible Way To Die',
  'A Lesson In Love',
  'A Lizard In A Woman’s Skin',
  'A Mighty Heart',
  'A Monster Calls',
  'A Most Violent Year',
  'A Night at the Opera',
  'A Nightmare On Elm Street',
  'A Nightmare On Elm Street 2: Freddy’s Revenge',
  'A Nightmare On Elm Street 3: Dream Warriors',
  'A Nightmare On Elm Street 4: The Dream Master',
  'A Nightmare On Elm Street 5: The Dream Child',
  'A Pigeon Sat on a Branch Reflecting on Existence',
  'A Prairie Home Companion',
  'A Prayer Before Dawn',
  'A Quiet Passion',
  'A Quiet Place In The Country',
  'A Quiet Place Part II',
  'A Room For Romeo Brass',
  'A Room With A View',
  'A Safe Place',
  'A Scanner Darkly',
  'A Scene at the Sea',
  'A Serious Man',
  'A Ship Bound for India',
  'A Single Man',
  'A Star Is Born (2018)',
  'A Summer at Grandpa’s',
  'A Swedish Love Story',
  'A Tale of Springtime',
  'A Tale of Two Sisters',
  'A Time To Love and A Time To Die',
  'A Very Long Engagement',
  'A Visitor to a Museum',
  'A Wrinkle In Time',
  'A.I. Artificial Intelligence',
  'Abattoir',
  'About Schmidt',
  'Accident',
  'Ace In The Hole',
  'Across the Universe',
  'Ad Astra',
  'Adam Green’s Aladdin',
  'Adam Resurrected',
  'Adaptation',
  'Adoration',
  'Adult World',
  'Adventureland',
  'Aeon Flux',
  'After Hours',
  'After The Rehearsal',
  'Afterschool',
  'Age of Consent',
  'Aguirre, The Wrath Of God (Aguirre, der Zorn Gottes)',
  'Ain’t Them Bodies Saints',
  'Akira',
  'Alexandria…Why?',
  'Ali',
  'Ali: Fear Eats The Soul',
  'Alice',
  'Alice Doesn’t Live Here Anymore',
  'Alice in the Cities',
  'Alice in Wonderland',
  'Alien',
  'Alien 3',
  'Alien: Covenant',
  'Alien: Resurrection',
  'Aliens',
  'Alita: Battle Angel',
  'All About My Mother',
  'All Is Lost',
  'All Monsters Attack',
  'All or Nothing',
  'All Quiet on the Western Front',
  'All That Jazz',
  'All The Real Girls',
  'All These Women',
  'Alléluia',
  'Almanac of Fall',
  'Almayer’s Folly',
  'Almost Famous',
  'Alphaville',
  'Alps',
  'Always Shine',
  'Amarcord',
  'Amelie',
  'Amer',
  'American Animals',
  'American Beauty',
  'American Gangster',
  'American Gigolo',
  'American Graffiti',
  'American History X',
  'American Honey',
  'American Hustle',
  'American Mary',
  'American Psycho',
  'Amistad',
  'Ammonite',
  'Amour',
  'An Actor’s Revenge',
  'An American In Paris',
  'An American Werewolf in London',
  'An Elephant Sitting Still',
  'An Evening With Beverly Luff Linn',
  'Anatomy of a Relationship',
  'And God Created Woman',
  'And The Fifth Horseman is Fear',
  'And The Ship Sails On',
  'Angel Heart',
  'Angel-A',
  'Angst',
  'Anguish',
  'Anna Christie',
  'Anna Karenina',
  'Annie Get Your Gun',
  'Annie Hall',
  'Annihilation',
  'Anomalisa',
  'Another Earth',
  'Another Year',
  'Ant-Man',
  'Ant-Man and the Wasp',
  'Antichrist',
  'Antiporno',
  'Antiviral',
  'Antoine and Colette',
  'Apocalypse Now',
  'Apostle',
  'Apt Pupil',
  'Aquaman',
  'Arabian Nights: Volume 1 – The Restless One',
  'Arabian Nights: Volume 2 The Desolate One',
  'Arabian Nights: Volume 3 The Enchanted One',
  'Archangel',
  'Archenemy',
  'Ariel',
  'Arrival',
  'Artists and Models',
  'As Tears Go By',
  'Ashes Of Time Redux',
  'Ashik Kerib',
  'Assassin’s Creed',
  'Assassination Nation',
  'Assault on Precinct 13',
  'At Close Range',
  'Atomic Blonde',
  'Atonement',
  'Attenberg',
  'Au Revoir Les Enfants',
  'Audition',
  'Auto Focus',
  'Autumn Sonata',
  'Ava',
  'Avatar',
  'Avengers: Age of Ultron',
  'Avengers: Endgame',
  'Avengers: Infinity War',
  'Away From Her',
  'Away We Go',
  'À Bout De Souffle (Breathless)',
  'Baby Driver',
  'Back to the Future',
  'Back to the Future II',
  'Back To The Future Part III',
  'Bad Boys',
  'Bad Boys II',
  'Bad Education',
  'Bad Lieutenant',
  'Bad Lieutenant: Port Of Call New Orleans',
  'Bad Times at the El Royale',
  'Badlands',
  'Ballad Of Narayama',
  'Ballast',
  'Bamboozled',
  'Band of Outsiders (Bande à part)',
  'Baraka',
  'Barbarella',
  'Barfly',
  'Barry Lyndon',
  'Barton Fink',
  'Basic Instinct',
  'Baskin',
  'Bastards',
  'Batman',
  'Batman & Robin',
  'Batman Begins',
  'Batman Forever',
  'Batman Returns',
  'Batman V Superman: Dawn of Justice',
  'Battle In Heaven',
  'Battle Royale',
  'Battleship Potemkin',
  'Bay of Angels',
  'Be Kind Rewind',
  'Beach Rats',
  'Beast',
  'Beasts of No Nation',
  'Beasts Of The Southern Wild',
  'Beatriz At Dinner',
  'Beau Travail',
  'Beauty and the Beast (1978)',
  'Becky',
  'Bed & Board',
  'Beetlejuice',
  'Before I Wake',
  'Before Midnight',
  'Before Sunrise',
  'Before Sunset',
  'Beginners',
  'Begotten',
  'Behind The Candelabra',
  'Being John Malkovich',
  'Being There',
  'Bell Book and Candle',
  'Belladonna of Sadness',
  'Belle De Jour',
  'Bellflower',
  'Belly',
  'Benny’s Video',
  'Berberian Sound Studio',
  'Bernie',
  'Betty Blue',
  'Beware Of A Holy Whore',
  'Beyond The Black Rainbow',
  'Beyond the Hills',
  'Big Bad Wolves',
  'Big Eyes',
  'Big Fish',
  'Big Trouble in Little China',
  'Bill and Ted’s Bogus Journey',
  'Bill and Ted’s Excellent Adventure',
  'Bird',
  'Bird Box',
  'Birdman',
  'Birds of Prey: And the Fantabulous Emancipation of One Harley Quinn',
  'Birth',
  'Birth of a Nation',
  'Biutiful',
  'Black ’47',
  'Black Bear',
  'Black Book',
  'Black Christmas',
  'Black Christmas (2019)',
  'Black is King',
  'Black Jack',
  'Black Moon',
  'Black Mother',
  'Black Narcissus',
  'Black Panther',
  'Black Sabbath',
  'Black Snow',
  'Black Sunday',
  'Black Swan',
  'Blackhat',
  'BlacKkKlansman',
  'Blade II',
  'Blade Runner',
  'Blade Runner 2049',
  'Blanche',
  'Blast Of Silence',
  'Blaze',
  'Blind Chance',
  'Blindspotting',
  'Bliss',
  'Blissfully Yours',
  'Blonde Venus',
  'Blood And Black Lace',
  'Blood For Dracula',
  'Blood From The Mummy’s Tomb',
  'Blood Simple',
  'Blow Out',
  'Blow The Man Down',
  'Blow-Up',
  'Blue',
  'Blue Is The Warmest Colour',
  'Blue Jay',
  'Blue Ruin',
  'Blue Valentine',
  'Blue Velvet',
  'Boarding Gate',
  'Bob le Flambeur',
  'Body Heat',
  'Bones',
  'Bonnie And Clyde',
  'Boogie Nights',
  'Boom!',
  'Borgman',
  'Born To Be Blue',
  'Bottle Rocket',
  'Bound',
  'Bound For Glory',
  'Boxer’s Omen (Mo)',
  'Boy',
  'Boy Meets Girl',
  'Boyhood',
  'Boys Don’t Cry',
  'Boyz In The Hood',
  'BPM (Beats Per Minute)',
  'Braid',
  'Bram Stoker’s Dracula',
  'Brand Upon the Brain!',
  'Brawl in Cell Block 99',
  'Brazil',
  'Breakfast On Pluto',
  'Breaking The Waves',
  'Brewster McCloud',
  'Brick',
  'Brick Lane',
  'Bride of Chucky',
  'Bride of Reanimator',
  'Brief Encounter',
  'Bright Star',
  'Brightburn',
  'Brigsby Bear',
  'Bring Me The Head of Alfredo Garcia',
  'Bringing Out The Dead',
  'Brink of Life',
  'Brokeback Mountain',
  'Broken',
  'Broken Blossoms',
  'Broken Circle Breakdown',
  'Broken Embraces',
  'Broken Flowers',
  'Bronson',
  'Brooklyn',
  'Bubba Ho-Tep',
  'Bubble',
  'Buffalo ’66',
  'Buffalo Bill and the Indians, or Sitting Bull’s History Lesson',
  'Buffy the Vampire Slayer',
  'Bug',
  'Bullhead',
  'Bullitt',
  'Bumblebee',
  'Bunny and the Bull',
  'Buried',
  'Burn After Reading',
  'Burning',
  'Bus Stop',
  'Bushwick',
  'Business is Business',
  'Buster’s Mal Heart',
  'But I’m A Cheerleader',
  'Butch Cassidy and the Sundance Kid',
  'Butterfly',
  'Butterfly Kiss',
  'Buzzard',
  'By The Sea',
  'Byzantium',
  'Cabaret',
  'Caché (Hidden)',
  'Cairo Station',
  'Cake',
  'Calamity Jane',
  'California Split',
  'Call Me By Your Name',
  'Calm With Horses',
  'Caltiki, The Immortal Monster',
  'Calvaire',
  'Calvary',
  'Cam',
  'Camera Buff',
  'Can You Ever Forgive Me?',
  'Candyman',
  'Candyman: Farewell to the Flesh',
  'Cape Fear',
  'Cape Fear',
  'Capote',
  'Captain America: Civil War',
  'Captain America: The First Avenger',
  'Captain America: The Winter Soldier',
  'Captain Fantastic',
  'Captain Marvel',
  'Caravaggio',
  'Careful',
  'Carlito’s Way',
  'Carnal Knowledge',
  'Carne',
  'Carnival of Souls',
  'Carol',
  'Carrie',
  'Carrie (2013)',
  'Carriers',
  'Casa De Lava',
  'Casa De Mi Padre',
  'Casablanca',
  'Casino',
  'Casino Royale',
  'Castle Freak',
  'Castle in the Sky',
  'Cat People',
  'Cat People',
  'Catch 22',
  'Catch Me Daddy',
  'Catch Me If You Can',
  'Cathy Come Home',
  'Cedar Rapids',
  'Cemetery of Splendour',
  'Censor',
  'Certain Women',
  'Certified Copy',
  'Chained For Life',
  'Changeling',
  'Chaplin',
  'Chappie',
  'Charley Varrick',
  'Charlie and The Chocolate Factory',
  'Che Part 1 (The Argentine)',
  'Che Part 2 (Guerrilla)',
  'Cheap Thrills',
  'Chi-raq',
  'Chicago',
  'Child’s Play',
  'Child’s Play (2019)',
  'Child’s Play 2',
  'Child’s Play 3',
  'Childhood of a Leader',
  'Children',
  'Children Of Men',
  'Chinatown',
  'Chinese Roulette',
  'Chizuko’s Younger Sister',
  'Chloe',
  'Chocolat',
  'Choke',
  'Christine (2016)',
  'Christopher Robin',
  'Chungking Express',
  'Cinema Paradiso',
  'Citizen Kane',
  'City Lights',
  'City of God',
  'City of Women',
  'Claire’s Camera',
  'Claire’s Knee',
  'Clan of the Cave Bear',
  'Cleo from 5 to 7',
  'Climax',
  'Clockers',
  'Close Encounters Of The Third Kind',
  'Closer',
  'Cloud Atlas',
  'Clouds of Sils Maria',
  'Clown',
  'Clueless',
  'Cockfighter',
  'Coco',
  'Code 46',
  'Code Unknown',
  'Coeur Fidele',
  'Coffee and Cigarettes',
  'Cold Mountain',
  'Cold Souls',
  'Cold War',
  'Collateral',
  'Collective: Unconscious',
  'Colossal',
  'Colour Out of Space',
  'Colt 45',
  'Columbus',
  'Come and See',
  'Come Back to the 5 & Dime Jimmy Dean, Jimmy Dean',
  'Come To Daddy',
  'Come True',
  'Coming Home',
  'Compliance',
  'Compulsion',
  'Computer Chess',
  'Confessions',
  'Confessions of a Dangerous Mind',
  'Conquest',
  'Contagion',
  'Container',
  'Contempt (Le Mépris)',
  'Control',
  'Cooties',
  'Cop Car',
  'Coraline',
  'Cosmopolis',
  'Cosmos',
  'Counting',
  'Cowards Bend The Knee',
  'CQ',
  'Cracks',
  'Crash',
  'Creed',
  'Creepshow',
  'Creepshow 2',
  'Creepy',
  'Cries and Whispers',
  'Crime & Punishment',
  'Crimes and Misdemeanors',
  'Crimson Peak',
  'Crisis',
  'Cronos',
  'Crouching Tiger, Hidden Dragon',
  'Cruising',
  'Cry Baby',
  'Cuadecuc, Vampir',
  'Cube',
  'Cul-de-sac',
  'Cult of Chucky',
  'Curse of Chucky',
  'Cymbeline',
  'Da 5 Bloods',
  'Da Sweet Blood of Jesus',
  'Dagon',
  'Daguerréotypes',
  'Daisies',
  'Damnation',
  'Damsel',
  'Dance Me Outside',
  'Dance of Reality',
  'Dancer In The Dark',
  'Dances With Wolves',
  'Danger Diabolik',
  'Dangerous Beauty',
  'Daniel Isn’t Real',
  'Dark City',
  'Dark Habits',
  'Dark Horse',
  'Dark River',
  'Dark Shadows',
  'Darkest Hour',
  'Darlin’',
  'Das Boot',
  'Dating Amber',
  'Daughters of Darkness',
  'Dawn of the Dead',
  'Dawn of the Dead (2004)',
  'Dawn of the Planet of the Apes',
  'Day for Night',
  'Day of the Dead',
  'Daybreakers',
  'Days Of Being Wild',
  'Days Of Heaven',
  'Dazed and Confused',
  'Dead Man',
  'Dead Man Walking',
  'Dead Man’s Letters',
  'Dead Man’s Shoes',
  'Dead of Night',
  'Dead Pigs',
  'Dead Ringers',
  'Dead Silence',
  'Deadpool',
  'Deadpool 2',
  'Dean',
  'Dear Wendy',
  'Death and Transfiguration',
  'Death Becomes Her',
  'Death By Hanging',
  'Death In Venice',
  'Death Note',
  'Death Occurred Last Night',
  'Death Proof',
  'Decline of Western Civilization',
  'Decoder',
  'Deep Cover',
  'Deep End',
  'Deep Red',
  'Def By Temptation',
  'Delicatessen',
  'Deliverance',
  'Dementia (Daughter of Horror)',
  'Demon Seed',
  'Demons of the Mind',
  'Depraved',
  'Der Bomberpilot',
  'Dersu Uzala',
  'Despair',
  'Desperate Living',
  'Destiny',
  'Destroy All Monsters',
  'Destroyer',
  'Detective',
  'Detroit',
  'Die Hard',
  'Dinner in America',
  'Distant Voices, Still Lives',
  'District 9',
  'Diva',
  'Django Kill',
  'Django Unchained',
  'Do The Right Thing',
  'Doctor Sleep',
  'Doctor Strange',
  'Doctor X',
  'Doctor Zhivago',
  'Documenteur',
  'Dodes’ka-den',
  'Dog Eat Dog',
  'Dogs Don’t Wear Pants',
  'Dogtooth',
  'Dogville',
  'Dolemite Is My Name',
  'Dollhouse',
  'Dom Hemingway',
  'Dominion: Prequel to the Exorcist',
  'Domino',
  'Don’t Breathe',
  'Don’t Look Now',
  'Don’t Torture A Duckling',
  'Don’t Worry He Won’t Get Far On Foot',
  'Donkey Skin',
  'Donnie Darko',
  'Doomsday',
  'Dope',
  'Double Happiness',
  'Double Indemnity',
  'Down By Law',
  'Down In The Valley',
  'Down Terrace',
  'Down With Love',
  'Dr. Goldfoot and the Girl Bombs',
  'Dr. Jekyll and Mr. Hyde',
  'Dr. No',
  'Dr. Phibes Rises Again',
  'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
  'Dracula',
  'Dracula: Pages from a Virgin’s Diary',
  'Drag Me to Hell',
  'Dreams',
  'Dreams',
  'Dredd',
  'Dressed To Kill',
  'Drive',
  'Drop Dead Gorgeous',
  'Drugstore Cowboy',
  'Drunken Angel',
  'Dumbo',
  'Dumplings',
  'Dune',
  'Dunkirk',
  'Dust Devil',
  'Dust In The Wind',
  'E.T. The Extra-Terrestrial',
  'Eagle Vs. Shark',
  'Eastern Promises',
  'Easy A',
  'Easy Rider',
  'Eat Pray Love',
  'Eaux d’Artifice',
  'Ebirah Horror of the Deep',
  'Ed Wood',
  'Eden Lake',
  'Edge of Tomorrow',
  'Edward II',
  'Edward Scissorhands',
  'Effi Briest',
  'Eight Men Out',
  'Eighth Grade',
  'Eika Katappa',
  'El Chicano',
  'El Topo',
  'Election',
  'Electra Glide In Blue',
  'Elena',
  'Elephant',
  'Elevator To The Gallows (Ascenseur pour l’échafaud)',
  'Elizabeth Harvest',
  'Elle',
  'Eloge de L’amour',
  'Elvira Madigan',
  'Elysium',
  'Ema',
  'Embrace Of The Serpent',
  'Emma.',
  'Emperor Tomato Ketchup (Short)',
  'Enemy',
  'Enter The Dragon',
  'Enter The Void',
  'Entertainment',
  'Equals',
  'Eraserhead',
  'Erik The Conqueror',
  'Erin Brockovich',
  'Essential Killing',
  'Eternal Sunshine of The Spotless Mind',
  'Etoile',
  'Eva',
  'Even Dwarfs Started Small',
  'Event Horizon',
  'Everlasting Moments',
  'Everybody Wants Some!!',
  'Everyday',
  'Everything Is Illuminated',
  'Evil Dead',
  'Evil Dead II',
  'Evolution',
  'Ex Machina',
  'Excalibur',
  'Excision',
  'eXistenZ',
  'Exotica',
  'Experimenter',
  'Extra Ordinary',
  'Extremely Wicked, Shockingly Evil and Vile',
  'Eyes Wide Shut',
  'Eyes Without A Face',
  'F for Fake',
  'Face to Face',
  'Faces Places',
  'Fahrenheit 451',
  'Fall of the House of Usher',
  'Fallen Angels',
  'Falstaff (Chimes at Midnight)',
  'Family Nest',
  'Family Plot',
  'Fando y Lis',
  'Fanny and Alexander',
  'Fantastic Mr. Fox',
  'Far From Heaven',
  'Far From The Madding Crowd (1967)',
  'Far From The Madding Crowd (2015)',
  'Fargo',
  'Fast Color',
  'Faster, Pussycat! Kill! Kill!',
  'Fat City',
  'Fata Morgana',
  'Faults',
  'Faust',
  'Faust',
  'Fear and Loathing In Las Vegas',
  'Fear Of Fear',
  'Fellini – Satyricon',
  'Fellini’s Casanova',
  'Female Trouble',
  'Fight Club',
  'Fighting With My Family',
  'Filth',
  'Final Girls',
  'Finding Nemo',
  'Fireworks',
  'First Blood',
  'First Cow',
  'First Name: Carmen',
  'First Reformed',
  'Fish Tank',
  'Fistful Of Dollars',
  'Five Easy Pieces',
  'Flaming Star',
  'Flesh For Frankenstein',
  'Flesh+Blood',
  'Floating Weeds',
  'Florida Man',
  'Following',
  'Footprints (Le Orme)',
  'For A Few Dollars More',
  'For Ellen',
  'For Ever Mozart',
  'Forbidden Games',
  'Force Majeure',
  'Ford V Ferrari',
  'Four Flies On Grey Velvet',
  'Four Times that Night',
  'Fox and His Friends',
  'Foxcatcher',
  'Frances Ha',
  'Frank',
  'Frankenstein',
  'Frankenweenie',
  'Frankie and Johnny',
  'Frantz',
  'Freaks',
  'Freaky',
  'Freddy’s Dead: The Final Nightmare',
  'Free Fire',
  'Free State of Jones',
  'Frenzy',
  'Frida',
  'Friday the 13th',
  'Friday the 13th Part 2',
  'Friday the 13th Part III',
  'Friday the 13th: The Final Chapter',
  'From Beyond',
  'From The East',
  'From the Life of the Marionettes',
  'Fruit of Paradise',
  'Fruitvale Station',
  'Full Metal Jacket',
  'Funeral Parade of Roses',
  'Funny Games',
  'Funny Games',
  'Funny Girl',
  'Fur: An Imaginary Portrait Of Diane Arbus',
  'Furia',
  'Ga-Ga: Glory to the Heroes',
  'Gangs of New York',
  'Gangster Squad',
  'Ganja & Hess',
  'Garage',
  'Gate of Flesh',
  'Gattaca',
  'Gemini',
  'Gemini Man',
  'Genova',
  'Gentlemen Broncos',
  'Gerald’s Game',
  'Gerry',
  'Get Out',
  'Get The Gringo (How I Spent My Summer Vacation)',
  'Ghidorah The Three Headed Monster',
  'Ghost Dog: The Way of the Samurai',
  'Ghost in the Shell (1995)',
  'Ghost in the Shell (2017)',
  'Ghost Stories',
  'Ghost World',
  'Ghostbusters',
  'Ghostbusters 2',
  'Ghosts… Of The Civil Dead',
  'Gigi',
  'Giliap',
  'Ginger & Rosa',
  'Ginger Snaps',
  'Girl Asleep',
  'Girl on the Bridge',
  'Girl on the Third Floor',
  'Girl Walks Into a Bar',
  'Girl with a Pearl Earring',
  'Girlhood',
  'Gladiator',
  'Glitterbug',
  'Go Down Death',
  'God Bless America',
  'God’s Own Country',
  'God’s Pocket',
  'Godard Mon Amour',
  'Gods Of The Plague',
  'Godzilla',
  'Godzilla (1954)',
  'Godzilla and Mothra: The Battle for Earth',
  'Godzilla Raids Again',
  'Godzilla Vs Gigan',
  'Godzilla Vs Hedorah',
  'Godzilla Vs Mechagodzilla',
  'Godzilla Vs Megalon',
  'Godzilla vs. Biollante',
  'Godzilla vs. Destoroyah',
  'Godzilla vs. King Ghidorah',
  'Godzilla Vs. Kong',
  'Godzilla vs. Mechagodzilla II',
  'Godzilla vs. SpaceGodzilla',
  'Godzilla: King of the Monsters',
  'Gohatto',
  'Golem',
  'Gone Girl',
  'Gone With The Wind',
  'Good Favour',
  'Good Night And Good Luck',
  'Good Time',
  'Good Will Hunting',
  'Goodfellas',
  'Goodnight Mommy',
  'Gothic',
  'Goto, Island of Love',
  'Gozu',
  'Graduate First',
  'Graduation',
  'Graffiti Bridge',
  'Gran Torino',
  'Grass',
  'Gravity',
  'Gray’s Anatomy',
  'Grease',
  'Great Expectations',
  'Greed',
  'Green Room',
  'Green Street',
  'Greenberg',
  'Greener Grass',
  'Gremlins',
  'Gremlins 2: The New Batch',
  'Greta',
  'Gretel & Hansel',
  'Grey Gardens',
  'Groundhog Day',
  'Guardians of the Galaxy',
  'Guardians of the Galaxy Vol. 2',
  'Guava Island',
  'Gummo',
  'Guys and Dolls',
  'Hail Mary',
  'Hail, Caesar!',
  'Half Nelson',
  'Halloween',
  'Halloween',
  'Halloween (2018)',
  'Halloween 2',
  'Ham on Rye',
  'Hamlet',
  'Hammett',
  'Hanagatami',
  'Hanna',
  'Happy Death Day',
  'Happy End',
  'Happy New Year, Colin Burstead',
  'Happy Together',
  'Happy-Go-Lucky',
  'Hard Candy',
  'Hard Core Logo',
  'Hard Eight',
  'Hard To Be A God',
  'Hardcore',
  'Hardware',
  'Harold and Maude',
  'Harry Potter & The Deathly Hallows Part 1',
  'Harry Potter & The Deathly Hallows Part 2',
  'Harry Potter & The Goblet of Fire',
  'Harry Potter & The Half Blood Prince',
  'Harry Potter & The Order of the Phoenix',
  'Harry Potter and the Chamber of Secrets',
  'Harry Potter and the Prisoner of Azkaban',
  'Haute Tension',
  'Haywire',
  'Häxan',
  'He Got Game',
  'Head',
  'Head Against The Wall',
  'Head of the Family',
  'Heart of Glass',
  'Heartbeats (Les Amours Imaginaires)',
  'Hearts Beat Loud',
  'Heat',
  'Heathers',
  'Heaven’s Gate',
  'Heavenly Creatures',
  'Hedwig and the Angry Inch',
  'Helas Pour Moi',
  'Hell or High Water',
  'Hellboy',
  'Hellboy (2019)',
  'Hellboy II: The Golden Army',
  'Hellions',
  'Hellraiser',
  'Help!',
  'Helter Skelter',
  'Her',
  'Her Smell',
  'Here Alone',
  'Here Comes The Devil',
  'Hereditary',
  'Hermitage',
  'Hero',
  'Hidden Agenda',
  'High and Low',
  'High Flying Bird',
  'High Heels',
  'High Life',
  'High-Rise',
  'Highway 61',
  'History of the World: Part 1',
  'Hobo With A Shotgun',
  'Hocus Pocus',
  'Hold The Dark',
  'Holiday',
  'Hollow Man',
  'Holy Motors',
  'Honey Boy',
  'Honeydripper',
  'Horns',
  'Horse Thief',
  'Hot Fuzz',
  'Hotel Artemis',
  'Hotel By The River',
  'Hotel Transylvania',
  'Hour of the Wolf',
  'House (Hausu)',
  'House By The Cemetery',
  'House of 1000 Corpses',
  'House of Flying Daggers',
  'House of Tolerance',
  'Housewife',
  'How to Marry a Millionaire',
  'Howl',
  'Howl’s Moving Castle',
  'Hud',
  'Hugo',
  'Human Highway',
  'Humpday',
  'Hunger',
  'Hunt for the Wilderpeople',
  'Hustlers',
  'I Am Cuba',
  'I Am Love',
  'I Am Not a Serial Killer',
  'I Am The Pretty Thing That Lives In The House',
  'I Can’t Sleep',
  'I Care A Lot',
  'I Heart Huckabees',
  'I Killed My Mother (J’ai tué ma mère)',
  'I Live In Fear',
  'I Melt With You',
  'I Origins',
  'I Saw The Devil',
  'I Stand Alone (Seul Contre Tous)',
  'I Think We’re Alone Now',
  'I Trapped The Devil',
  'I Vampiri',
  'I Vitelloni',
  'I Want To Go Home',
  'I Want You',
  'I’m A Cyborg, But That’s Okay',
  'I’m Not There',
  'I’m So Excited!',
  'I’m Thinking of Ending Things',
  'I’m Your Woman',
  'I, Daniel Blake',
  'I, Tonya',
  'Ida',
  'If Beale Street Could Talk',
  'If….',
  'Ikiru',
  'Il Bidone',
  'Images',
  'Immoral Tales',
  'In a Glass Cage',
  'In a Lonely Place',
  'In A Valley of Violence',
  'In A Year Of Thirteen Moons',
  'In Another Country',
  'In Bruges',
  'In Cold Blood',
  'In Dreams',
  'In the Bedroom',
  'In The Cut',
  'In The Heart of the Sea',
  'In The Loop',
  'In The Mood For Love',
  'In The Mouth of Madness',
  'In The Presence of a Clown',
  'In The Tall Grass',
  'Inauguration of the Pleasure Dome',
  'Incendies',
  'Inception',
  'Indiana Jones and the Last Crusade',
  'Indiana Jones and the Temple of Doom',
  'Inglourious Basterds',
  'Ingrid Goes West',
  'Inherent Vice',
  'Inland Empire',
  'Innocence',
  'Innocence Unprotected',
  'Inside Llewyn Davis',
  'Insignificance',
  'Insomnia',
  'Interstellar',
  'Interview With The Vampire',
  'Intervista',
  'Into The Wild',
  'Intolerable Cruelty',
  'Invaders From Mars',
  'Invasion of Astro Monster',
  'Invincible',
  'Invocation of My Demon Brother',
  'IP5',
  'Irma Vep',
  'Iron Man',
  'Iron Man 2',
  'Iron Man 3',
  'Irréversible',
  'Island of Lost Souls',
  'Isle of Dogs',
  'Isolation',
  'It',
  'It Comes at Night',
  'It Felt Like Love',
  'It Follows',
  'It Happened At The World’s Fair',
  'It Happened One Night',
  'It Rains On Our Love',
  'It’s A Wonderful Life',
  'It’s Kind Of A Funny Story',
  'It’s Only The End Of The World',
  'Ivan’s Childhood',
  'Jabberwocky',
  'Jackie',
  'Jackie Brown',
  'Jacob’s Ladder',
  'Jacquot de Nantes',
  'Jakob’s Wife',
  'James and the Giant Peach',
  'Jane B. par Agnès V.',
  'Jane Eyre',
  'Japón',
  'Jarhead',
  'Jauja',
  'Jaws',
  'Jeanne Dielman, 23, quai du commerce, 1080 Bruxelles',
  'Jennifer’s Body',
  'Jeux d’Enfants',
  'JFK',
  'Jigoku',
  'Jigsaw',
  'Jimmy’s Hall',
  'Joe',
  'John Wick',
  'John Wick: Chapter 2',
  'Johnny Colt',
  'Johnny Guitar',
  'Jojo Rabbit',
  'Joker',
  'Journeyman',
  'Jubilee',
  'Judas and the Black Messiah',
  'Jude',
  'Judex',
  'Judy',
  'Jules et Jim',
  'Julien Donkey Boy',
  'Juliet of the Spirits',
  'Julieta',
  'Junebug',
  'Juno',
  'Jupiter Ascending',
  'Jurassic Park',
  'Jurassic World',
  'Jurassic World: Fallen Kingdom',
  'Justice League',
  'Kafka',
  'Kagemusha',
  'Kamikaze Girls',
  'Kamouraska',
  'Kate Plays Christine',
  'Katie Tippel',
  'Katzelmacher',
  'Keanu',
  'Keep Your Right Up',
  'Keyhole',
  'Kick Ass',
  'Kid Galahad',
  'Kika',
  'Kiki’s Delivery Service',
  'Kill Bill Vol. 1',
  'Kill Bill Vol. 2',
  'Kill List',
  'Kill Your Darlings',
  'Kill, Baby Kill',
  'Killer Joe',
  'Killer of Sheep',
  'Killer’s Kiss',
  'Killing Them Softly',
  'King Kong',
  'King Kong Vs. Godzilla',
  'King Lear',
  'King of the Hill',
  'Kings Of Summer',
  'Kings of the Road (Im Lauf der Zeit)',
  'Kiss Kiss Bang Bang',
  'Kiss of the Damned',
  'Kissing Candice',
  'Klute',
  'Knife In The Water',
  'Knife+Heart',
  'Knight of Cups',
  'Knives Out',
  'Kong: Skull Island',
  'Koyaanasquatsi',
  'Krisha',
  'Kubo and the Two Strings',
  'Kumiko the Treasure Hunter',
  'Kung Fu Master!',
  'Kustom Kar Kommandos',
  'Kwaidan',
  'L’Avventura',
  'L’une Chante, l’Autre Pas',
  'L.A. Confidential',
  'La Belle et la Bête',
  'La Collectionneuse',
  'La Dolce Vita',
  'La Haine',
  'La Jetée',
  'La La Land',
  'La Notte',
  'La Peau Douce (The Soft Skin)',
  'La Pointe Courte',
  'La Strada',
  'La Vie En Rose',
  'Labyrinth',
  'Labyrinth of Passion',
  'Lacombe, Lucien',
  'Ladies and Gentlemen, the Fabulous Stains',
  'Lady Bird',
  'Lady in the Water',
  'Lady Macbeth',
  'Lady Snowblood',
  'Lady Snowblood Song of Vengeance',
  'Lady Vengeance',
  'Laggies',
  'Land Ho!',
  'Land of Plenty',
  'Lars And The Real Girl',
  'Last and First Men',
  'Last Days',
  'Last Flag Flying',
  'Last House on the Left',
  'Last Life in the Universe',
  'Last Year at Marienbad',
  'Lasting (Nieulotne)',
  'Late August, Early September',
  'Laurence Anyways',
  'Law of Desire',
  'Lawless',
  'Lawrence Of Arabia',
  'Layer Cake',
  'Léon Morin, Priest',
  'Léon: The Professional',
  'Le Bonheur (Happiness)',
  'Le Boucher',
  'Le Cercle Rouge',
  'Le Chinoise',
  'Le Doulos',
  'Le Feu Follet',
  'Le Petit Soldat',
  'Le Signe du Lion',
  'Lean on Pete',
  'Leave No Trace',
  'Leaving Las Vegas',
  'Legends of the Fall',
  'Lemon',
  'Lemonade',
  'Lemonade Joe',
  'Lenny',
  'Les Amants',
  'Les Amants Du Pont Neuf (The Lovers on the Bridge)',
  'Les Carabiniers',
  'Les Créatures',
  'Les Demoiselles de Rochefort',
  'Les Misérables',
  'Let Me In',
  'Let The Corpses Tan',
  'Let The Right One In',
  'Let The Sunshine In',
  'Let Them All Talk',
  'Let’s Scare Jessica To Death',
  'Leviathan',
  'Licorice Pizza',
  'Life During Wartime',
  'Life Is A Bed of Roses',
  'Life is Beautiful',
  'Life of Brian',
  'Life of Pi',
  'Light Sleeper',
  'Like Me',
  'Lili Marleen',
  'Limbo',
  'Limitless',
  'Lincoln',
  'Lions Love',
  'Liquid Sky',
  'Lisa and The Devil',
  'Lisztomania',
  'Little Big Man',
  'Little Birds',
  'Little Children',
  'Little Women',
  'Little Woods',
  'Live Flesh',
  'Locke',
  'Logan',
  'Logan Lucky',
  'Lola',
  'Lola',
  'Lolita',
  'London Boulevard',
  'Lone Wolf and Cub: Baby Cart in Peril',
  'Lone Wolf and Cub: Baby Cart in the Land of Demons',
  'Lone Wolf and Cub: Baby Cart to Hades',
  'Lone Wolf and Cub: Sword of Vengeance',
  'Lone Wolf and Cub: White Heaven in Hell',
  'Lone Wolf: Baby Cart at the River Styx',
  'Looking for Eric',
  'Looper',
  'Lords Of Salem',
  'Lost Highway',
  'Lost In Translation',
  'Lost River',
  'Louder Than Bombs',
  'Lourdes',
  'Love',
  'Love',
  'Love & Mercy',
  'Love Affair, or the Case of the Missing Switchboard Operator',
  'Love and Friendship',
  'Love In The Afternoon (Chloe In The Afternoon) (L’amour l’après-midi)',
  'Love Is Colder Than Death',
  'Love Liza',
  'Love Me Tender',
  'Love Song For Bobby Long',
  'Love Unto Death',
  'Loveless',
  'Loving',
  'Loving Vincent',
  'Low Down',
  'Lucifer Rising',
  'Lucy',
  'Ludwig',
  'Lust For Life',
  'Luz',
  'M',
  'M (1951)',
  'M. Butterfly',
  'Maîtresse',
  'Macbeth',
  'Macbeth',
  'MacGruber',
  'Mad Max',
  'Mad Max 2',
  'Mad Max Beyond Thunderdome',
  'Mad Max: Fury Road',
  'Madadayo',
  'Madame Bovary',
  'Made in U.S.A.',
  'Madeline’s Madeline',
  'Madonna and Child',
  'Maelström',
  'Magic',
  'Magic Mike',
  'Magic Mike XXL',
  'Magnificent Obsession',
  'Magnolia',
  'Mala Noche',
  'Malcolm & Marie',
  'Malcolm X',
  'Maleficent',
  'Malina',
  'Malpertuis',
  'Mama',
  'Man Is Not Bird',
  'Man Of Steel',
  'Man on Fire',
  'Man On The Moon',
  'Man on the Roof',
  'Man with a Movie Camera',
  'Manchester By The Sea',
  'Manderlay',
  'Mandy',
  'Manglehorn',
  'Manhattan',
  'Manhunter',
  'Maniac',
  'Mank',
  'Maps to the Stars',
  'Marathon Man',
  'Margin Call',
  'Margot At The Wedding',
  'Marie Antoinette',
  'Marketa Lazarová',
  'Marnie',
  'Marriage Story',
  'Mars Attacks!',
  'Martha',
  'Martha Marcy May Marlene',
  'Martin',
  'Martyrs',
  'Mary & Max',
  'Mary Poppins',
  'Masculin Fémenin',
  'MASH',
  'Mata Hari',
  'Matador',
  'Matewan',
  'Matthias & Maxime',
  'Mauvais Sang (Bad Blood) (The Night Is Young)',
  'Mayhem',
  'Mélo',
  'McCabe & Mrs.Miller',
  'Me and You and Everyone We Know',
  'Meadowland',
  'Mean Creek',
  'Mean Streets',
  'Meek’s Cutoff',
  'Melancholia',
  'Melvin & Howard',
  'Memento',
  'Merantau',
  'Meshes of the Afternoon',
  'Message From The King',
  'Messiah of Evil',
  'Metropolis',
  'Michael Clayton',
  'Michael Collins',
  'Mickey and the Bear',
  'Micmacs',
  'Microcosmos',
  'Mid90s',
  'Midnight Cowboy',
  'Midnight Special',
  'Midsommar',
  'Milk',
  'Mill of the Stone Women',
  'Millenium Actress',
  'Miller’s Crossing',
  'Milou en Mai',
  'Mimic',
  'Minari',
  'Mindhorn',
  'Minority Report',
  'Mirror Mirror',
  'Mirrors',
  'Misery',
  'Mishima: A Life in Four Chapters',
  'Miss Peregrine’s Home for Peculiar Children',
  'Mission: Impossible',
  'Mission: Impossible – Fallout',
  'Mission: Impossible – Ghost Protocol',
  'Mission: Impossible – Rogue Nation',
  'Mission: Impossible II',
  'Mission: Impossible III',
  'Mississippi Burning',
  'Mississippi Grind',
  'Mississippi Mermaid',
  'Mister Lonely',
  'Mistress America',
  'Misunderstood',
  'Mo’ Better Blues',
  'Modern Times',
  'Mogul Mowgli',
  'Mom and Dad',
  'Mommy',
  'Moneyball',
  'Monty Python and the Holy Grail',
  'Mood Indigo',
  'Moon',
  'Moonlight',
  'Moonrise Kingdom',
  'Mortal Transfer',
  'Morvern Callar',
  'Mother',
  'Mother Kusters Goes To Heaven',
  'Mother!',
  'Motherless Brooklyn',
  'Mothra Vs Godzilla',
  'Moulin Rouge!',
  'Mr. Arkadin',
  'Mr. Klein',
  'Mr. Nobody',
  'Mr. Roosevelt',
  'Mr. Turner',
  'Ms. 45',
  'Much Ado About Nothing',
  'Mud',
  'Mudbound',
  'Mulholland Drive',
  'Multiple Maniacs',
  'Munich',
  'Mur Murs',
  'Murder Party',
  'Murder, My Sweet',
  'Muriel',
  'Murmur of the Heart',
  'Museum Hours',
  'Music in Darkness',
  'Mustang',
  'Mute',
  'My 20th Century',
  'My American Uncle (Mon oncle d’Amérique)',
  'My Beautiful Laundrette',
  'My Blueberry Nights',
  'My Darling Clementine',
  'My Life as a Zucchini',
  'My Neighbour Totoro',
  'My Night At Maud’s (Ma Nuit Chez Maud)',
  'My Own Private Idaho',
  'My Son, My Son, What Have Ye Done?',
  'My Summer of Love',
  'My Winnipeg',
  'Mysterious Object at Noon',
  'Mysterious Skin',
  'Mystery Team',
  'Mystery Train',
  'Nacho Libre',
  'Naked',
  'Naked Lunch',
  'Napoleon Dynamite',
  'Naqoyquatsi',
  'Narc',
  'Nashville',
  'Natural Born Killers',
  'Nausicaä of the Valley of the Wind',
  'Near Dark',
  'Nebraska',
  'Nenette et Boni',
  'Neruda',
  'Nerve',
  'Never Grow Old',
  'Never Let Me Go',
  'Never Rarely Sometimes Always',
  'New Nightmare',
  'New York, New York',
  'News From Home',
  'Next Door',
  'Night Moves',
  'Night Of The Demon',
  'Night of the Living Dead',
  'Night on Earth',
  'Night Owls',
  'Night Tide',
  'Nightcrawler',
  'Nightmare Alley',
  'Nightmare Cinema',
  'Nights of Cabiria',
  'Nikita',
  'No',
  'No Country For Old Men',
  'No End',
  'No Regrets for Our Youth',
  'No Sudden Move',
  'Noah',
  'Nocturama',
  'Nocturnal Animals',
  'Nomadland',
  'Non-Fiction',
  'North By Northwest',
  'Nosferatu',
  'Nosferatu the Vampyre (Nosferatu Phantom Der Nacht)',
  'Notorious',
  'Notre Musique',
  'Nowhere Boy',
  'Nuits Rouges',
  'Nymphomaniac Vol 1',
  'Nymphomaniac Vol 2',
  'O Brother, Where Art Thou?',
  'O Lucky Man!',
  'O-Bi, O-Ba – The End of Civilisation',
  'Oblivion',
  'Observe And Report',
  'Ocean’s Eleven',
  'Ocean’s Thirteen',
  'Oculus',
  'Odd Man Out',
  'Officer Downe',
  'Okja',
  'Old Joy',
  'Oldboy',
  'Oliver Twist',
  'Olivia',
  'On A Clear Day You Can See Forever',
  'On Body and Soul',
  'On The Beach',
  'On The Road',
  'On The Rocks',
  'On The Town',
  'On War',
  'Once Upon A Time In America',
  'Once Upon a Time in Anatolia',
  'Once Upon A Time In The West',
  'Once Upon a Time… In Hollywood',
  'Ondine',
  'One and Two',
  'One Flew Over The Cuckoo’s Nest',
  'One From The Heart',
  'One Hour Photo',
  'One Hundred and One Nights',
  'One Hundred Mornings',
  'One More Time With Feeling',
  'One Wonderful Sunday',
  'Onibaba',
  'Only God Forgives',
  'Only Lovers Left Alive',
  'Only The Brave',
  'Open Range',
  'Orchestra Rehearsal',
  'Orlando',
  'Orpheus',
  'Othello',
  'Our Day Will Come',
  'Our Lady of the Turks',
  'Out Of Sight',
  'Out of the Furnace',
  'Out of the Past',
  'Overlord',
  'Pacific Rim',
  'Paddington',
  'Paddington 2',
  'Paganini Horror',
  'Pain and Glory',
  'Palm Springs',
  'Palo Alto',
  'Pan',
  'Pan’s Labyrinth',
  'Pandora’s Box',
  'Panic Room',
  'Paper Moon',
  'Papillon',
  'Paprika',
  'Paradise Hills',
  'Paradise: Faith',
  'Paradise: Hope',
  'Paradise: Love',
  'Pariah',
  'Paris Is Burning',
  'Paris, Je T’Aime',
  'Paris, Texas',
  'Pasolini',
  'Pass Over',
  'Passion',
  'Pastoral To Die In The Country',
  'Pat Garrett & Billy The Kid',
  'Patagonia',
  'Paterson',
  'Paths of Glory',
  'Patty Hearst',
  'Paul',
  'Pauline At the Beach (Pauline à la plage)',
  'Pawn Sacrifice',
  'Pecker',
  'Pee-Wee’s Big Adventure',
  'Pepi, Luci, Bom and Other Girls Like Mom',
  'Perfect Blue',
  'Performance',
  'Persona',
  'Personal Shopper',
  'Perversion Story',
  'Pet Sematary',
  'Pete’s Dragon',
  'Peterloo',
  'Petulia',
  'Phantom Thread',
  'Phenomena',
  'Phoenix',
  'Pi',
  'Pickup on South Street',
  'Picnic at Hanging Rock',
  'Piercing',
  'Pierrot Le Fou (Crazy Pete)',
  'Pina',
  'Pineapple Express',
  'Pink Flamingos',
  'Pink Floyd The Wall',
  'Pink Narcissus',
  'Piranha 3D',
  'Pirates of the Caribbean: At World’s End',
  'Pirates of the Caribbean: Dead Man’s Chest',
  'Pirates of the Caribbean: On Stranger Tides',
  'Pirates of the Caribbean: The Curse of the Black Pearl',
  'Planet of the Apes',
  'Planet of the Vampires',
  'Platoon',
  'Pleasantville',
  'Poison',
  'Pokémon Detective Pikachu',
  'Pola X',
  'Polar',
  'Pollock',
  'Poltergeist',
  'Polyester',
  'Polytechnique',
  'Pontypool',
  'Ponyo',
  'Popeye',
  'Populaire',
  'Porco Rosso',
  'Port of Call',
  'Portrait of a Lady on Fire',
  'Possession',
  'Possessor',
  'Possum',
  'Post Mortem',
  'Post Tenebras Lux',
  'Powaqqatsi',
  'Predator',
  'Predestination',
  'Pretty Baby',
  'Pretty Persuasion',
  'Prevenge',
  'Pride & Prejudice',
  'Prince Avalanche',
  'Princess Mononoke',
  'Prison',
  'Prisoners',
  'Private Life',
  'Prometheus',
  'Promised Land',
  'Promising Young Woman',
  'Psycho',
  'Psycho 2',
  'Psycho III',
  'Puce Moment',
  'Pulp Fiction',
  'Punch Drunk Love',
  'Punisher: War Zone',
  'Purple Noon (Plein Soleil)',
  'Pusher',
  'Pusher II',
  'Pusher III',
  'Puzzle of a Downfall Child',
  'Quackser Fortune Has a Cousin in the Bronx',
  'Queen Christina',
  'Queen of Blood',
  'Queen of Earth',
  'Querelle',
  'Quintet',
  'Rabbit’s Moon',
  'Rabid (2019)',
  'Raging Bull',
  'Raiders Of The Lost Ark',
  'Raise The Red Lantern',
  'Raising Arizona',
  'Rampart',
  'Rampo Noir',
  'Ran',
  'Rango',
  'Rashomon',
  'Ratcatcher',
  'Ravenous',
  'Raw',
  'Re-Animator',
  'Read My Lips',
  'Ready or Not',
  'Rear Window',
  'Rebecca',
  'Rebel Without A Cause',
  'Reconstruction',
  'Red Beard',
  'Red Hook Summer',
  'Red Road',
  'Redes',
  'Relaxer',
  'Renoir',
  'Repo Man',
  'Repo! The Genetic Opera',
  'Repulsion',
  'Requiem For A Dream',
  'Rescue Dawn',
  'Reservoir Dogs',
  'Resident Evil',
  'Resident Evil: Afterlife',
  'Resident Evil: Apocalypse',
  'Resident Evil: Extinction',
  'Resident Evil: Retribution',
  'Resident Evil: The Final Chapter',
  'Restless',
  'Results',
  'Return Of The Jedi',
  'Revanche',
  'Revenge',
  'Revenge',
  'Revolutionary Road',
  'Rhapsody in August',
  'Ride In The Whirlwind',
  'Ride Lonesome',
  'Ride the High Country',
  'Ride With The Devil',
  'Rio Bravo',
  'Rio Das Mortes',
  'Rio Grande',
  'Rise of the Planet of the Apes',
  'River of Grass',
  'River of No Return',
  'River’s Edge',
  'Road Games',
  'Road To Perdition',
  'Roadgames',
  'Roadkill',
  'Robocop',
  'Rocketman',
  'Rogue One: A Star Wars Story',
  'Roma',
  'Roma',
  'Roman Holiday',
  'Roman J. Israel, Esq.',
  'Romeo + Juliet',
  'Romper Stomper',
  'Room',
  'Room For Rent',
  'Rope',
  'Roselyne and the Lions',
  'Rosemary’s Baby',
  'Rosetta',
  'Roy Colt and Winchester Jack',
  'Ruby Sparks',
  'Rumble Fish',
  'Run Lola Run',
  'Rupture',
  'Rush',
  'Rushmore',
  'Russian Ark',
  'Russian Symphony',
  'Rust And Bone',
  'Ryan’s Daughter',
  'Saboteur',
  'Safe',
  'Saint Laurent',
  'Saint Maud',
  'Sakuran',
  'Salò, or the 120 Days of Sodom',
  'Salome',
  'Salvador',
  'Samsara',
  'Sanjuro',
  'Sanshiro Sugata',
  'Sanshiro Sugata Part II',
  'Santa Sangre',
  'Saraband',
  'Satan’s Brew',
  'Satan’s Slaves',
  'Saturday Night Fever',
  'Savages',
  'Saving Private Ryan',
  'Saw',
  'Saw II',
  'Saw III',
  'Saw IV',
  'Saw V',
  'Saw VI',
  'Saw VII: The Final Chapter',
  'Sawdust and Tinsel',
  'Sátántangó',
  'Scandal',
  'Scanners',
  'Scarecrow',
  'Scarface',
  'Scarlet Diva',
  'Scary Stories to Tell in the Dark',
  'Scenes from a Marriage',
  'Schindler’s List',
  'Schizopolis',
  'Scorpio Rising',
  'Scott Pilgrim Vs The World',
  'Scream',
  'Scream 2',
  'Scream 3',
  'Scream 4',
  'Scum',
  'Se7en',
  'Sea Fever',
  'Seabiscuit',
  'Seance on a Wet Afternoon',
  'Sebastiane',
  'Seberg',
  'Seconds',
  'Secret Ceremony',
  'Secretary',
  'Seed of Chucky',
  'Selah and the Spades',
  'Self/less',
  'Selma',
  'Serial Mom',
  'Session 9',
  'Seven Samurai',
  'Seven Stages to Achieve Eternal Bliss',
  'Sex, Lies And Videotape',
  'Sexy Beast',
  'Shadow of a Doubt',
  'Shadow of the Vampire',
  'Shadows',
  'Shallow Grave',
  'Shame',
  'Shame',
  'Shanghai Express',
  'Shaun Of The Dead',
  'Shazam!',
  'She Dies Tomorrow',
  'Sherlock Jr.',
  'Shirkers',
  'Shiva Baby',
  'Shock Corridor',
  'Shoot The Piano Player (Tirez Sur Le Pianiste)',
  'Shoplifters',
  'Short Cuts',
  'Short Term 12',
  'Shotgun Stories',
  'Showgirls',
  'Shutter Island',
  'Siberia',
  'Sicario',
  'Side Effects',
  'Sidewalls',
  'Sideways',
  'Sightseers',
  'Signs',
  'Silence',
  'Silence (2012)',
  'Silent Hill',
  'Silent Light',
  'Silent Running',
  'Silver Linings Playbook',
  'Simon Killer',
  'Simon, The Magician',
  'Sin City',
  'Sin City: A Dame to Kill For',
  'Sin Nombre',
  'Singin’ in the Rain',
  'Sinister',
  'Sisters',
  'Skate Kitchen',
  'Skyfall',
  'Slack Bay',
  'Slacker',
  'Sleeping Beauty',
  'Sleepless in Seattle',
  'Sleepy Hollow',
  'Slice',
  'Slow Motion (Every Man for Himself)  (Sauve Que Peut (La Vie)',
  'Slow West',
  'Slumdog Millionaire',
  'Small Change',
  'Small Crimes',
  'Smiles Of A Summer Night',
  'Smiley Face',
  'Smokin’ Aces',
  'Snatch',
  'Snow Angels',
  'Snow Falling on Cedars',
  'Snow White and The Huntsman',
  'Snowbound',
  'Snowpiercer',
  'Snowtown',
  'So Pretty',
  'Solaris',
  'Solaris',
  'Soldier of Orange',
  'Solo: A Star Wars Story',
  'Some Like It Hot',
  'Someone Great',
  'Somers Town',
  'Something in the Air',
  'Something Wild',
  'Somewhere',
  'Son of Godzilla',
  'Son of Saul',
  'Song of Granite',
  'Song to Song',
  'Songs from the Second Floor',
  'Sorcerer',
  'Sorry to Bother You',
  'Soul',
  'Sound of Metal',
  'Sound Of My Voice',
  'Sound of Noise',
  'Source Code',
  'Southbound',
  'Southland Tales',
  'Soylent Green',
  'Speed Racer',
  'Spellbound',
  'Spencer',
  'Spetters',
  'Spider',
  'Spider Man: Homecoming',
  'Spider-Man',
  'Spider-Man 2',
  'Spider-Man: Far From Home',
  'Spider-Man: Into the Spider-Verse',
  'Spiral',
  'Spirit Of The Beehive',
  'Spirited Away',
  'Splice',
  'Split',
  'Spring',
  'Spring Breakers',
  'Spy Game',
  'Stalag 17',
  'Stalker',
  'Stan & Ollie',
  'Stand By Me',
  'Star Trek',
  'Star Trek Beyond',
  'Star Trek Into Darkness',
  'Star Wars',
  'Star Wars: Episode I – The Phantom Menace',
  'Star Wars: Episode II – Attack of the Clones',
  'Star Wars: Episode III – Revenge of the Sith',
  'Star Wars: The Force Awakens',
  'Star Wars: The Last Jedi',
  'Stardust Memories',
  'Starfish',
  'Starman',
  'Starry Eyes',
  'Starship Troopers',
  'Stay',
  'Stereo',
  'Steve Jobs',
  'Stockholm',
  'Stoker',
  'Stolen Kisses',
  'Strange Days',
  'Stranger By The Lake',
  'Stranger on the Third Floor',
  'Stranger Than Paradise',
  'Strangers on a Train',
  'Straw Dogs',
  'Stray Dog',
  'Streets of Fire',
  'Streetwise',
  'Stronger',
  'Stroszek',
  'Submarine',
  'Submergence',
  'Suburban Gothic',
  'Subway',
  'Successive Slidings of Pleasure (Glissements progressifs du plaisir)',
  'Sucker Punch',
  'Suddenly, Last Summer',
  'Sugar',
  'Suicide Squad',
  'Summer Interlude',
  'Summer of 84',
  'Summer of Sam',
  'Summer with Monika',
  'Sun Choke',
  'Sunrise',
  'Sunset Boulevard',
  'Sunset Song',
  'Sunshine',
  'Super',
  'Super 8',
  'Super Dark Times',
  'Superman',
  'Surveillance',
  'Suspiria',
  'Suspiria (2018)',
  'Swallow',
  'Sweeney Todd: The Demon Barber of Fleet Street',
  'Sweet Charity',
  'Sweet Movie',
  'Sweet Smell of Success',
  'Swing Time',
  'Swiss Army Man',
  'Sympathy for Mr. Vengeance',
  'Synchronic',
  'Syndromes and a Century',
  'Synecdoche, New York',
  'Syriana',
  'T-Rex',
  'T2 Trainspotting',
  'Tabu',
  'Take Me Away!',
  'Take Shelter',
  'Take This Waltz',
  'Tale of Tales',
  'Tales From Earthsea',
  'Tales from the Gimli Hospital',
  'Talk To Her',
  'Tamara Drewe',
  'Tampopo',
  'Tangerine',
  'Targets',
  'Taxi Driver',
  'Team America: World Police',
  'Tenderness of the Wolves',
  'Tenebre',
  'Tenet',
  'Terminator 2: Judgement Day',
  'Terror of Mechagodzilla',
  'Tesla',
  'Tetro',
  'Tetsuo II: Body Hammer',
  'Tetsuo: The Iron Man',
  'That Obscure Object of Desire',
  'Thérèse Desqueyroux',
  'The 1,000 Eyes of Dr. Mabuse',
  'The 10th Victim',
  'The 13th Warrior',
  'The 400 Blows',
  'The A-Team',
  'The ABCs of Death',
  'The Abominible Dr. Phibes',
  'The Adjustment Bureau',
  'The Adventures Of Baron Munchausen',
  'The Adventures of Robin Hood',
  'The Aerial',
  'The Age of Innocence',
  'The Alchemist Cookbook',
  'The American',
  'The American Astronaut',
  'The American Friend',
  'The American Soldier',
  'The Angel’s Share',
  'The Angelic Conversation',
  'The Annihilation of Fish',
  'The Army of Shadows',
  'The Arrival of Joachim Stiller',
  'The Art of Self Defence',
  'The Artist',
  'The Ascent',
  'The Assassin',
  'The Assassination Of Jesse James By The Coward Robert Ford',
  'The Assassination of Richard Nixon',
  'The Assistant',
  'The Autopsy of Jane Doe',
  'The Avengers',
  'The Aviator',
  'The Babadook',
  'The Bad and the Beautiful',
  'The Bad Batch',
  'The Bad Sleep Well',
  'The Ballad of Buster Scruggs',
  'The Ballad of Cable Hogue',
  'The Band Wagon',
  'The Banishment',
  'The Beach',
  'The Beach Bum',
  'The Beaches of Agnès',
  'The Beast',
  'The Beguiled',
  'The Beguiled (2017)',
  'The Belly of an Architect',
  'The Best Years of Our Lives',
  'The Big Blue',
  'The Big Lebowski',
  'The Big Night',
  'The Big Sick',
  'The Big Trail',
  'The Bird With The Crystal Plumage',
  'The Birdcage',
  'The Birds',
  'The Bitter Tears Of Petra Von Kant',
  'The Black Book (Reign of Terror)',
  'The Black Dahlia',
  'The Blackcoat’s Daughter',
  'The Bling Ring',
  'The Blood on Satan’s Claw',
  'The Blue Lamp',
  'The Box',
  'The Boy Friend',
  'The Boys From Fengkuei',
  'The Bride of Frankenstein',
  'The Bride With White Hair',
  'The Brood',
  'The Brother From Another Planet',
  'The Brothers Bloom',
  'The Brown Bunny',
  'The Burning Plain',
  'The Cabin In The Woods',
  'The Cabinet of Dr. Caligari',
  'The Cage',
  'The Canal',
  'The Canyons',
  'The Cell',
  'The Cider House Rules',
  'The Circle',
  'The City Of Lost Children',
  'The Claim',
  'The Clowns',
  'The Coca-Cola Kid',
  'The Colour of Money',
  'The Colour of Pomegranates',
  'The Comedy',
  'The Comfort of Strangers',
  'The Company of Wolves',
  'The Conformist',
  'The Congress',
  'The Conjuring',
  'The Conjuring 2',
  'The Conversation',
  'The Cooler',
  'The Corpse Bride',
  'The Cotton Club',
  'The Craft',
  'The Cremator',
  'The Criminal',
  'The Crossing Guard',
  'The Crow',
  'The Crying Game',
  'The Cured',
  'The Curious Case Of Benjamin Button',
  'The Curse of Frankenstein',
  'The Damned United',
  'The Dancer',
  'The Danish Girl',
  'The Darjeeling Limited',
  'The Dark Knight',
  'The Dark Knight Rises',
  'The Day a Pig Fell Into the Well',
  'The Day After',
  'The Day He Arrives',
  'The Day Shall Come',
  'The Day the Earth Stood Still',
  'The Dead Don’t Die',
  'The Dead Zone',
  'The Death and Life of John F. Donovan',
  'The Death of Dick Long',
  'The Death of Maria Malibran',
  'The Death of Stalin',
  'The Deep Blue Sea',
  'The Deer Hunter',
  'The Departed',
  'The Descendants',
  'The Descent',
  'The Devil Rides Out',
  'The Devil Wears Prada',
  'The Devil’s Doorway',
  'The Devil’s Eye',
  'The Devil’s Rejects',
  'The Devils',
  'The Devils Backbone',
  'The Diary of a Teenage Girl',
  'The Disappearance of Eleanor Rigby: Her',
  'The Disappearance of Eleanor Rigby: Him',
  'The Disaster Artist',
  'The Discarnates',
  'The Diving Bell and the Butterfly',
  'The Docks of New York',
  'The Double',
  'The Double Life of Véronique',
  'The Dreamers',
  'The Driver',
  'The Duke of Burgundy',
  'The East',
  'The Editor',
  'The Elephant Man',
  'The Empire Strikes Back',
  'The End of the Tour',
  'The Endless',
  'The Enigma Of Kaspar Hauser',
  'The Exorcist',
  'The Exorcist 3',
  'The Extraordinary Adventures of Adèle Blanc-Sec',
  'The Eyes of My Mother',
  'The Face of an Angel',
  'The Fall',
  'The Falling',
  'The Farewell',
  'The Favourite',
  'The Fearless Vampire Killers',
  'The Field Guide to Evil',
  'The Fifth Cord',
  'The Fifth Element',
  'The Fighter',
  'The Fisher King',
  'The Fits',
  'The Florida Project',
  'The Flower of My Secret',
  'The Fly',
  'The Fog',
  'The Forbidden Room',
  'The Fortune',
  'The Fountain',
  'The Fourth Man',
  'The French Connection',
  'The Funhouse',
  'The Future',
  'The Garden',
  'The Getaway',
  'The Girl Can’t Help It',
  'The Girl on a Motorcycle',
  'The Girl Who Knew Too Much',
  'The Girl With All The Gifts',
  'The Girl With The Dragon Tattoo',
  'The Girlfriend Experience',
  'The Gleaners & I',
  'The Go-Between',
  'The Godfather',
  'The Godfather Part II',
  'The Gold Rush',
  'The Good German',
  'The Good Girl',
  'The Good Thief',
  'The Good, The Bad And The Ugly',
  'The Graduate',
  'The Grand Budapest Hotel',
  'The Grandmaster',
  'The Grapes of Wrath',
  'The Greasy Strangler',
  'The Great Beauty',
  'The Great Dictator',
  'The Great Silence',
  'The Green Ray',
  'The Grey',
  'The Grudge',
  'The Guest',
  'The Hallow',
  'The Handmaiden',
  'The Hands of Orlac',
  'The Hangover',
  'The Hangover Part II',
  'The Hangover Part III',
  'The Happening',
  'The Hateful Eight',
  'The Haunting',
  'The Heart Is Deceitful Above All Things',
  'The Heart Machine',
  'The Hellbenders',
  'The Hidden Fortress',
  'The Hills Have Eyes (2006)',
  'The Hired Hand',
  'The Hole in the Ground',
  'The Holy Mountain',
  'The Homesman',
  'The Horror of Frankenstein',
  'The Horrors of Malformed Men',
  'The Hours',
  'The House of Mirth',
  'The House Of The Devil',
  'The House That Jack Built',
  'The Howling',
  'The Hudsucker Proxy',
  'The Hunchback of Notre Dame',
  'The Hunger',
  'The Hunger Games',
  'The Hunt for Red October',
  'The Hunter',
  'The Hurricane',
  'The Hustler',
  'The Ice Storm',
  'The Idiot',
  'The Iguana with the Tongue of Fire',
  'The Illusionist',
  'The Imaginarium of Doctor Parnassus',
  'The Imitation Game',
  'The Immigrant',
  'The Immortal Story',
  'The Immortals',
  'The Imposter',
  'The Incredible Hulk',
  'The Indian Runner',
  'The Informant!',
  'The Innkeepers',
  'The Innocents',
  'The Innocents (2016)',
  'The Insider',
  'The Intruder',
  'The Invisible Woman',
  'The Invitation',
  'The Irishman',
  'The Kid',
  'The Killer Inside Me',
  'The Killing',
  'The Killing Fields',
  'The Killing of a Sacred Deer',
  'The King',
  'The King Of Comedy',
  'The King Of Marvin Gardens',
  'The King’s Speech',
  'The Kingdom of Naples',
  'The Lady Eve',
  'The Lady from Shanghai',
  'The Ladykillers',
  'The Lair of the White Worm',
  'The Last Battle',
  'The Last Black Man in San Francisco',
  'The Last Command',
  'The Last Days On Mars',
  'The Last Detail',
  'The Last Metro',
  'The Last of England',
  'The Last of the Mohicans',
  'The Last Picture Show',
  'The Last Temptation Of Christ',
  'The Laundromat',
  'The Legend Of Kaspar Hauser',
  'The Leopard',
  'The Life Aquatic With Steve Zissou',
  'The Light Between Oceans',
  'The Lighthouse',
  'The Limey',
  'The Limits of Control',
  'The Little Hours',
  'The Little Stranger',
  'The Lives of Others',
  'The Lobster',
  'The Lodger',
  'The Lone Ranger',
  'The Long Day Closes',
  'The Long Dumb Road',
  'The Long Goodbye',
  'The Look of Love',
  'The Lord of the Rings: The Fellowship of the Ring',
  'The Lord of The Rings: The Return of the King',
  'The Lord of The Rings: The Two Towers',
  'The Lost City of Z',
  'The Lost Honour of Katharina Blum',
  'The Love Witch',
  'The Lower Depths',
  'The Lure',
  'The Machinist',
  'The Mad Hatter',
  'The Magic Flute',
  'The Magician',
  'The Magnificent Ambersons',
  'The Maltese Falcon',
  'The Man From London',
  'The Man Who Cried',
  'The Man Who Fell To Earth',
  'The Man Who Killed Don Quixote',
  'The Man Who Killed Hitler and Then the Bigfoot',
  'The Man Who Knew Too Much',
  'The Man Who Laughs',
  'The Man Who Loved Women',
  'The Man Who Wasn’t There',
  'The Manchurian Candidate (2004)',
  'The Marriage of Maria Braun',
  'The Martian',
  'The Masque of the Red Death',
  'The Master',
  'The Matrix',
  'The Matrix Reloaded',
  'The Matrix Revolutions',
  'The Mauritanian',
  'The Men Who Tread on the Tigers Tail',
  'The Merchant Of The Four Seasons',
  'The Meyerowitz Stories (New and Selected)',
  'The Midnight Meat Train',
  'The Midnight Sky',
  'The Mind’s Eye',
  'The Miracle Worker',
  'The Miseducation of Cameron Post',
  'The Monster',
  'The Monster Squad',
  'The Moon in the Gutter',
  'The Most Beautiful',
  'The Moth Diaries',
  'The Mothman Prophecies',
  'The Mountain',
  'The Neon Bible',
  'The Neon Demon',
  'The Nest',
  'The New World',
  'The New York Ripper',
  'The Nice Guys',
  'The Night Eats the World',
  'The Night Of The Hunter',
  'The Nightingale',
  'The Nightmare Before Christmas',
  'The Niklashausen Journey',
  'The Notorious Bettie Page',
  'The Nun',
  'The Old Man & The Gun',
  'The Omen',
  'The Orphanage',
  'The Other',
  'The Other (1999)',
  'The Other Side of the Wind',
  'The Pact II',
  'The Panic in Needle Park',
  'The Parallax View',
  'The Party',
  'The Passenger',
  'The Passion of Anna',
  'The Passion of Joan of Arc',
  'The Passion of the Christ',
  'The Peanut Butter Falcon',
  'The People vs. Larry Flint',
  'The Perfection',
  'The Perks of Being A Wallflower',
  'The Personal History of David Copperfield',
  'The Phantom Carriage',
  'The Phantom of the Opera',
  'The Pianist',
  'The Piano',
  'The Piano Teacher',
  'The Pit and The Pendulum',
  'The Place Beyond The Pines',
  'The Platform',
  'The Plea',
  'The Pledge',
  'The Portait of a Lady',
  'The Post',
  'The Postman Always Rings Twice',
  'The Prestige',
  'The Private Life of Sherlock Holmes',
  'The Proposition',
  'The Prowler',
  'The Purge',
  'The Purge: Anarchy',
  'The Purge: Election Year',
  'The Quick and the Dead',
  'The Quiet Duel',
  'The Raid',
  'The Raid 2',
  'The Rainbow Thief',
  'The Rapture',
  'The Reader',
  'The Red Shoes',
  'The Red Turtle',
  'The Reflecting Skin',
  'The Report',
  'The Return',
  'The Return of Godzilla',
  'The Return of the Prodigal Son',
  'The Revenant',
  'The Revenge of Frankenstein',
  'The Rhythm Section',
  'The Rider',
  'The Ring',
  'The Rite',
  'The River',
  'The Road',
  'The Roaring Twenties',
  'The Robe',
  'The Rock',
  'The Rocky Horror Picture Show',
  'The Role',
  'The Rover',
  'The Royal Tenenbaums',
  'The Ruins',
  'The Runaways',
  'The Sacrament',
  'The Saddest Music in the World',
  'The Savages',
  'The Scarlet Letter',
  'The Scent of Green Papaya',
  'The Science Of Sleep',
  'The Scouting Book for Boys',
  'The Sea of Trees',
  'The Searchers',
  'The Secret Life of Walter Mitty',
  'The Secret Of Roan Inish',
  'The Secret of the Grain',
  'The Secret Son',
  'The Selfish Giant',
  'The Serpent’s Egg',
  'The Servant',
  'The Seventh Continent',
  'The Seventh Seal',
  'The Seventh Victim',
  'The Shallows',
  'The Shape of Water',
  'The Shawshank Redemption',
  'The Shining',
  'The Shooting',
  'The Shout',
  'The Silence',
  'The Silence Of The Lambs',
  'The Silencing',
  'The Silent Partner',
  'The Sisters Brothers',
  'The Sixth Sense',
  'The Skeleton Twins',
  'The Skin I Live In',
  'The Slumber Party Massacre',
  'The Social Network',
  'The Sorcerers',
  'The Sound of Music',
  'The Sound of Silence',
  'The Spectacular Now',
  'The Squid and the Whale',
  'The State of Things',
  'The Station Agent',
  'The Story of Adele H',
  'The Straight Story',
  'The Strange Case of Dr. Jekyll and Miss Osbourne',
  'The Strange Colour of Your Body’s Tears',
  'The Strange Ones',
  'The Stranger',
  'The Strangers: Prey at Night',
  'The Stylist',
  'The Survivalist',
  'The Sweet Hereafter',
  'The Swimming Pool',
  'The Talented Mr. Ripley',
  'The Tango Lesson',
  'The Taste of Tea',
  'The Tempest',
  'The Tempest',
  'The Tenant',
  'The Terminator',
  'The Terrorizers',
  'The Texas Chainsaw Massacre',
  'The Texas Chainsaw Massacre 2',
  'The Theory of Everything',
  'The Thief of Paris',
  'The Thin Blue Line',
  'The Thin Red Line',
  'The Thing',
  'The Third Generation',
  'The Third Man',
  'The Thomas Crown Affair',
  'The Three Burials of Melquiades Estrada',
  'The Threepenny Opera',
  'The Town',
  'The Tracey Fragments',
  'The Tree Of Life',
  'The Trial',
  'The Tribe',
  'The Trip',
  'The Trouble With Harry',
  'The Truman Show',
  'The Truth About Charlie',
  'The Turin Horse',
  'The Turn of the Century',
  'The Twilight Saga: Breaking Dawn – Part 1',
  'The Twilight Saga: Breaking Dawn – Part 2',
  'The Twilight Saga: Eclipse',
  'The Twilight Saga: New Moon',
  'The Two Faces of January',
  'The Ugly Swans',
  'The Umbrellas Of Cherbourg',
  'The Unbearable Lightness of Being',
  'The Underneath',
  'The Unknown Girl',
  'The Untouchables',
  'The Usual Suspects',
  'The Vast of Night',
  'The Verdict',
  'The Village',
  'The Virgin Spring',
  'The Virgin Suicides',
  'The Voice of the Moon',
  'The Voices',
  'The Void',
  'The Wailing',
  'The Walker',
  'The Wanderers',
  'The War of Jan-Ken-Pon',
  'The War of the Worlds: Next Century',
  'The Warriors',
  'The Wedding Guest',
  'The Wheel (La Roue)',
  'The Whispering Star',
  'The White Ribbon',
  'The White Sheik',
  'The Wicker Man',
  'The Wild Bunch',
  'The Wild Child',
  'The Wind',
  'The Wind Rises',
  'The Wind That Shakes the Barley',
  'The Wind Will Carry Us',
  'The Wishing Tree',
  'The Witch',
  'The Witches of Eastwick',
  'The Wizard Of Oz',
  'The Wolf Man',
  'The Wolf of Snow Hollow',
  'The Wolf of Wall Street',
  'The Woman in Black',
  'The Woman Next Door',
  'The World’s End',
  'The Wormwood Star',
  'The Wrestler',
  'The Yards',
  'The Zero Theorem',
  'Thelma',
  'There Will Be Blood',
  'They Were Expendable',
  'Thief',
  'Thieves Like Us',
  'Things to Come',
  'Thirst',
  'Thirst',
  'This Is England',
  'This Movie Is Broken',
  'This Night',
  'Thor',
  'Thor: Ragnarok',
  'Thor: The Dark World',
  'Thoroughbreds',
  'Three Colours: Blue',
  'Three Colours: Red',
  'Three Colours: White',
  'Three Days of the Condor',
  'Three Kings',
  'Throne of Blood',
  'Through A Glass Darkly',
  'Throw Away Your Books, Rally in the Streets',
  'Thunderbolt & Lightfoot',
  'THX 1138',
  'Tideland',
  'Tie Me Up! Tie Me Down!',
  'Timbuktu',
  'Time Bandits',
  'Time Of The Wolf',
  'Timecrimes',
  'Tinker Tailor Soldier Spy',
  'Tiresia',
  'Titane',
  'Titus',
  'To Die For',
  'To Joy',
  'To Kill A Mockingbird',
  'To Live and Die in L.A.',
  'To The Devil a Daughter',
  'To The Wonder',
  'Todo Modo',
  'Tokyo Chorus',
  'Tokyo Drifter',
  'Tokyo Gore Police',
  'Tom at the Farm',
  'Tomb Raider',
  'Tomboy',
  'Tombstone',
  'Tone Deaf',
  'Toni Erdmann',
  'Too Late',
  'Top Gun',
  'Total Recall',
  'Touch of Evil',
  'Touchy Feely',
  'Tout Va Bien',
  'Tower',
  'Toy Story 4',
  'Tracks',
  'Traffic',
  'Train To Busan',
  'Training Day',
  'Trainspotting',
  'Trance',
  'Transcendence',
  'Trash Humpers',
  'Trees Lounge',
  'Trick ‘R Treat',
  'Triple 9',
  'Tristana',
  'Tron',
  'TRON: Legacy',
  'Tropical Malady',
  'Trouble Every Day',
  'True Grit',
  'True History of the Kelly Gang',
  'True Romance',
  'True Stories',
  'Turbo Kid',
  'Turkish Delight',
  'Twelve Monkeys',
  'TwentyFourSeven',
  'Twilight',
  'Twilight of the Ice Nymphs',
  'Twin Peaks: Fire Walk With Me',
  'Twister',
  'Two English Girls',
  'Two Lane Blacktop',
  'Two or Three Things I Know About Her (2 ou 3 choses que je sais d’elle)',
  'U-Turn',
  'Un Chien Andalou',
  'Un Flic',
  'Un Homme et Une Femme',
  'Unbreakable',
  'Unbroken',
  'Uncle Boonme Who Can Recall His Past Lives',
  'Uncut Gems',
  'Under The Cherry Moon',
  'Under The Shadow',
  'Under The Silver Lake',
  'Under The Skin',
  'Underground',
  'Undertow',
  'Underwater',
  'Underworld',
  'Une Femme Est Une Femme (A Woman Is a Woman)',
  'Une Femme Mariée',
  'Unforgiven',
  'Union City',
  'Unsane',
  'Unstoppable',
  'Up',
  'Upgrade',
  'Upstream Color',
  'Urge',
  'Us',
  'Uzak',
  'V for Vendetta',
  'Vagabond',
  'Valerian and the City of a Thousand Planets',
  'Valerie & Her Week of Wonders',
  'Valhalla Rising',
  'Vampire Circus',
  'Vampyr',
  'Vampyros Lesbos',
  'Van Diemens Land',
  'Vanishing Point',
  'Vanishing Waves',
  'Variety Lights',
  'Velvet Buzzsaw',
  'Velvet Goldmine',
  'Vendredi Soir',
  'Venom',
  'Veronika Voss',
  'Vertigo',
  'VFW',
  'Videodrome',
  'Vinyan',
  'Violet',
  'Visioneers',
  'Viva',
  'Viva Las Vegas',
  'Vivement Dimanche',
  'Vivre Sa Vie',
  'Viy',
  'Voice',
  'Volver',
  'Vox Lux',
  'Voyage of Time',
  'Waiting Women',
  'Wake In Fright',
  'Waking Life',
  'Walk The Line',
  'Walkabout',
  'Wall-E',
  'Wanda',
  'War for the Planet of the Apes',
  'War Horse',
  'War of the Worlds',
  'War Requiem',
  'Watchmen',
  'Water Lillies',
  'We Are The Best!',
  'We Are The Night',
  'We Need To Talk About Kevin',
  'Weekend',
  'Weirdos',
  'Wendy and Lucy',
  'Werckmeister Harmonies',
  'What Happened Was…',
  'What Have I Done To Deserve This?',
  'What Lies Beneath',
  'What Richard Did',
  'What’s the Matter with Helen?',
  'What’s Up, Doc?',
  'Where The Truth Lies',
  'Where The Wild Things Are',
  'Where’d You Go Bernadette',
  'While We’re Young',
  'Whiplash',
  'White Bird in a Blizzard',
  'White Christmas',
  'White Heat',
  'White Material',
  'White Of The Eye',
  'Whity',
  'Who Are You, Polly Maggoo?',
  'Who Framed Roger Rabbit',
  'Who’s Afraid Of Virginia Woolf?',
  'Who’s That Knocking At My Door',
  'Whore',
  'Widows',
  'Wiener-Dog',
  'Wild',
  'Wild At Heart',
  'Wild in the Country',
  'Wild Rose',
  'Wild Strawberries',
  'Wildlife',
  'Wildlike',
  'Wildling',
  'Willy Wonka & the Chocolate Factory',
  'Wind Chill',
  'Wings',
  'Wings Of Desire',
  'Winter Light',
  'Winter’s Bone',
  'Wish I Was Here',
  'Witchfinder General',
  'Wittgenstein',
  'Wolf Children',
  'Wolfwalkers',
  'Womb',
  'Women on the Verge of a Nervous Breakdown',
  'Wonder Woman',
  'Wonderland',
  'Wonderstruck',
  'Wonderwall',
  'Woodshock',
  'World On A Wire',
  'Wounds',
  'Woyzeck',
  'WR: Mysteries of the Organism',
  'Wuthering Heights',
  'Xanadu',
  'Y Tu Mamá También',
  'Year Of The Dog',
  'Yesterday',
  'Yi-Yi (A One and A Two)',
  'Yojimbo',
  'You Ain’t Seen Nothin’ Yet',
  'You Were Never Really Here',
  'You’re Next',
  'You, The Living',
  'Young Mr. Lincoln',
  'Young Person’s Guide to Cinema',
  'Your Highness',
  'Your Sister’s Sister',
  'Yourself and Yours',
  'Youth',
  'Youth In Revolt',
  'Yumeji',
  'Z for Zachariah',
  'Zama',
  'Zardoz',
  'Zazie Dans Le Métro',
  'Zero Dark Thirty',
  'Ziegfeld Follies',
  'Zodiac',
  'Zombi Child',
]

export const FILMS = [
  '10 Cloverfield Lane',
  '2001: A Space Odyssey',
  'Harry Potter and the Philosopher’s Stone',
  'I, Robot',
  'Charlie and The Chocolate Factory',
  'Ant-Man and the Wasp',
  'Midsommar',
  'Mary Poppins',
  'Nacho Libre',
  'Fantastic Mr. Fox',
  'Mr. Nobody',
  'Once Upon a Time… In Hollywood',
  'Groundhog Day',
  'Dazed and Confused',
  'Fight Club',
  'Coco',
  'Birdman',
  'King Kong',
  'Casino',
  'Jurassic World',
  'Hunt for the Wilderpeople',
  'Godzilla',
  'John Wick',
  'Boogie Nights',
  'Captain Marvel',
  'Bill and Ted’s Excellent Adventure',
  'Inglourious Basterds',
  'Baby Driver',
  'Day of the Dead',
  'Batman V Superman: Dawn of Justice',
  'Mulholland Drive',
  'Ocean’s Eleven',
  'Limitless',
  'Fargo',
  'Memento',
  'Barbarella',
  'Mission: Impossible – Ghost Protocol',
  'Hail, Caesar!',
  'Videodrome',
  'No Country For Old Men',
  'The Texas Chainsaw Massacre',
  'Rebecca',
  'The Lobster',
  'Jojo Rabbit',
  'Clueless',
  'American Beauty',
  'Big Trouble in Little China',
  'Full Metal Jacket',
  'Lawrence Of Arabia',
  'Amelie',
  'Lost In Translation',
  'Get Out',
  'Dune',
  'Monty Python and the Holy Grail',
  'Lucy',
  'In Bruges',
  'In The Loop',
  'Nightcrawler',
  'Kill Bill Vol. 2',
  'Edge of Tomorrow',
  'Cleo from 5 to 7',
  'Burn After Reading',
  'Dunkirk',
  'Interstellar',
  'Django Unchained',
  'Knives Out',
  'Eat Pray Love',
  'The Matrix Reloaded',
  'Licorice Pizza',
  'The Shawshank Redemption',
  'Starship Troopers',
  'The Death of Stalin',
  'Psycho',
  'The Favourite',
  'Easy A',
  'Snatch',
  'Sisters',
  'BlacKkKlansman',
  'La La Land',
  'Zodiac',
  'The Devil Wears Prada',
  'The Shape of Water',
  'Climax',
  'L.A. Confidential',
  'Sleepless in Seattle',
  'Sorry to Bother You',
  'The Big Lebowski',
  'Die Hard',
  'Heat',
  'Election',
  'Persona',
  'Tinker Tailor Soldier Spy',
  'Bad Boys',
  'Ghostbusters 2',
  'Apocalypse Now',
  'Nosferatu',
  'Keanu',
  'Mad Max',
  'Adventureland',
  'Harry Potter & The Half Blood Prince',
  'Blade II',
  'Jurassic World: Fallen Kingdom',
  'Jarhead',
  'A Star Is Born (2018)',
  'Mad Max: Fury Road',
  'Kubo and the Two Strings',
  'Big Fish',
  'Aliens',
  'Captain America: The First Avenger',
  'Deadpool',
  'Ex Machina',
  'Man on Fire',
  'Jurassic Park',
  'Halloween',
  '1917',
  'Mank',
  'I’m Not There',
  'Iron Man 2',
  'In The Mood For Love',
  'Man Of Steel',
  'Bumblebee',
  'Hold The Dark',
  'A Wrinkle In Time',
  'After Hours',
  'Hamlet',
  'Miss Peregrine’s Home for Peculiar Children',
  'Alien',
  'Bird',
  'London Boulevard',
  'Moneyball',
  'Back to the Future II',
  'Bad Education',
  'Harry Potter & The Deathly Hallows Part 1',
  'Batman Begins',
  'Friday the 13th: The Final Chapter',
  'American Gangster',
  '1984',
  'Kiki’s Delivery Service',
  'Friday the 13th Part 2',
  'Incendies',
  'Captain America: The Winter Soldier',
  'Mother!',
  'Hocus Pocus',
  'Hellboy',
  'Captain America: Civil War',
  'Buffy the Vampire Slayer',
  'Hustlers',
  'Magic Mike',
  'Batman & Robin',
  'Man with a Movie Camera',
  'A Quiet Place',
  'Atonement',
  'Les Misérables',
  'Gray’s Anatomy',
  'Gretel & Hansel',
  'Dracula',
  'Christopher Robin',
  'Boyhood',
  'Jude',
  'Juno',
  'Kong: Skull Island',
  'Lemonade',
  'Mommy',
  'Batman',
  'Mistress America',
  'A Quiet Place Part II',
  'Alice in Wonderland',
  'Black Panther',
  'A Nightmare On Elm Street 2: Freddy’s Revenge',
  'Catch Me If You Can',
  'Munich',
  'Everybody Wants Some!!',
  'Logan',
  'Bird Box',
  'Manhattan',
  'If Beale Street Could Talk',
  'Catch 22',
  'Aquaman',
  'Lost River',
  'Harry Potter & The Deathly Hallows Part 2',
  'Minority Report',
  'Insomnia',
  'Be Kind Rewind',
  'Alien 3',
  'Friday the 13th',
  'Oblivion',
  'A Nightmare On Elm Street',
  'John Wick: Chapter 2',
  'Dawn of the Dead',
  'Indiana Jones and the Temple of Doom',
  '300',
  'Mud',
  'Lolita',
  'Dr. Jekyll and Mr. Hyde',
  'Casablanca',
  'Blindspotting',
  'Black Swan',
  'Halloween 2',
  'Avatar',
  'Batman Forever',
  'MacGruber',
  'Malcolm X',
  'Edward Scissorhands',
  'Evil Dead',
  'Hot Fuzz',
  'Loving Vincent',
  'Inception',
  '12 Years A Slave',
  'A Hitchhiker’s Guide To The Galaxy',
  'Dope',
  'Inherent Vice',
  'Maleficent',
  'Coraline',
  'Chappie',
  'Alien: Resurrection',
  'E.T. The Extra-Terrestrial',
  'Malcolm & Marie',
  'Killing Them Softly',
  'Bonnie And Clyde',
  'Hellraiser',
  'Deadpool 2',
  'Enter The Void',
  'Hotel Transylvania',
  'Leaving Las Vegas',
  'Frankenstein',
  'Death Note',
  'Captain Fantastic',
  'Iron Man',
  'Blade Runner',
  'Manhunter',
  'Mission: Impossible III',
  'I’m Thinking of Ending Things',
  'Marriage Story',
  'Hereditary',
  'Batman Returns',
  'Magic Mike XXL',
  'Moon',
  'Evil Dead II',
  'Napoleon Dynamite',
  'Life of Brian',
  'I, Tonya',
  'Mary & Max',
  'Maîtresse',
  'Motherless Brooklyn',
  'M',
  'Iron Man 3',
  'Ghostbusters',
  'Bill and Ted’s Bogus Journey',
  'Manchester By The Sea',
  'Jennifer’s Body',
  'One Flew Over The Cuckoo’s Nest',
  'Beauty and the Beast (1978)',
  'Isle of Dogs',
  'American History X',
  'King Kong',
  'Intolerable Cruelty',
  'Modern Times',
  'Little Women',
  'Maniac',
  'Judas and the Black Messiah',
  'Grease',
  'Alien: Covenant',
  'Moonlight',
  'Back To The Future Part III',
  'Chicago',
  'Avengers: Age of Ultron',
  'Let Me In',
  'Jackie',
  'Let The Right One In',
  'Bones',
  'Joker',
  'Brokeback Mountain',
  'Lost Highway',
  'Mandy',
  'Dawn of the Planet of the Apes',
  'Back to the Future',
  'Atomic Blonde',
  'Michael Clayton',
  'Das Boot',
  'Gravity',
  'Being John Malkovich',
  'Evolution',
  'Jane Eyre',
  'A Nightmare On Elm Street 5: The Dream Child',
  'Melancholia',
  'Millenium Actress',
  'Mama',
  'District 9',
  'Carol',
  'Ms. 45',
  'Oliver Twist',
  'Harry Potter and the Prisoner of Azkaban',
  'Inside Llewyn Davis',
  'Citizen Kane',
  'Blade Runner 2049',
  'Black Sabbath',
  'Call Me By Your Name',
  'Guardians of the Galaxy Vol. 2',
  'Ant-Man',
  'Godzilla Vs. Kong',
  'Assassin’s Creed',
  'Doctor Strange',
  'Jupiter Ascending',
  'A Nightmare On Elm Street 3: Dream Warriors',
  'Mission: Impossible II',
  'James and the Giant Peach',
  'Birds of Prey: And the Fantabulous Emancipation of One Harley Quinn',
  'Jackie Brown',
  'A Cure For Wellness',
  'Guardians of the Galaxy',
  'Hellboy II: The Golden Army',
  'Eighth Grade',
  'Life During Wartime',
  'Joe',
  'Arrival',
  'Mishima: A Life in Four Chapters',
  '12 Angry Men',
  'Howl’s Moving Castle',
  'Cloud Atlas',
  'Gremlins',
  'Layer Cake',
  'Casino Royale',
  'Friday the 13th Part III',
  'O Brother, Where Art Thou?',
  'Avengers: Endgame',
  'Harry Potter & The Order of the Phoenix',
  'American Psycho',
  'King Kong Vs. Godzilla',
  'MASH',
  'Miller’s Crossing',
  'Donnie Darko',
  'Marie Antoinette',
  'Lars And The Real Girl',
  'Avengers: Infinity War',
  'Interview With The Vampire',
  'It’s A Wonderful Life',
  'Creed',
  'Mad Max 2',
  'Justice League',
  'Mid90s',
  'Moulin Rouge!',
  'Dumbo',
  'Finding Nemo',
  'Close Encounters Of The Third Kind',
  'Goodfellas',
  'Drive',
  'Jaws',
  '127 Hours',
  'Life of Pi',
  'Kill Bill Vol. 1',
  '28 Days Later',
  'Gladiator',
  'Mission: Impossible',
  'Life is Beautiful',
  'It Follows',
  'Child’s Play',
  'Ocean’s Thirteen',
  'Boyz In The Hood',
  'Logan Lucky',
  'Harry Potter and the Chamber of Secrets',
  'It',
  'Judy',
  'Into The Wild',
  'Good Will Hunting',
  'A Clockwork Orange',
  'Indiana Jones and the Last Crusade',
  'Doomsday',
  'Eraserhead',
  'Harry Potter & The Goblet of Fire',
  'Don’t Breathe',
  'Doctor Sleep',
  'Beetlejuice',
  'Ford V Ferrari',
  'Minari',
  'Kick Ass',
  'Honey Boy',
  'A Nightmare On Elm Street 4: The Dream Master',
  'Lady Bird',
  'Night of the Living Dead',
  'Moonrise Kingdom',
  'Eternal Sunshine of The Spotless Mind',
  'Lincoln',
]
